[package]
name = "mugle_wallet_api"
version = "5.1.0-alpha.1"
authors = ["Mugle Developers <mimblewimble@lists.launchpad.net>"]
description = "Mugle Wallet API"
license = "Apache-2.0"
repository = "https://github.com/mugleproject/mugle-wallet"
keywords = [ "crypto", "mugle", "mimblewimble" ]
exclude = ["**/*.mugle", "**/*.mugle2"]
edition = "2018"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
log = "0.4"
uuid = { version = "0.8", features = ["serde", "v4"] }
serde = "1"
rand = "0.6"
serde_derive = "1"
serde_json = "1"
easy-jsonrpc-mw = "0.5.4"
chrono = { version = "0.4.11", features = ["serde"] }
ring = "0.16"
base64 = "0.12"
ed25519-dalek = "1.0.0-pre.4"

mugle_wallet_libwallet = { path = "../libwallet", version = "5.1.0-alpha.1" }
mugle_wallet_config = { path = "../config", version = "5.1.0-alpha.1" }
mugle_wallet_impls = { path = "../impls", version = "5.1.0-alpha.1" }
mugle_wallet_util = { path = "../util", version = "5.1.0-alpha.1" }

[dev-dependencies]
serde_json = "1"
tempfile = "3.1"
